### ISSUE TITLE
Skate ToDo examples are broken

### ISSUE THREAD

**Issue by arthurevans** [vogloblinsky/web-components-benchmark#19]
In these two examples:

https://vogloblinsky.github.io/web-components-benchmark/demos/todomvc/skatejs-lit-html/
https://vogloblinsky.github.io/web-components-benchmark/demos/todomvc/skatejs-preact/

The ToDo app isn't working right: hitting Enter doesn't add a ToDo item.

All the other versions of the ToDo demo seemed to work, and the Skate demos for pascal's triangle did, too, so it's just something about these two. I was wondering what they were doing to get the "Edit 50 ToDo items" time down so low--the next lowest is 86ms, but these two are listed as 5ms and 0ms, respectively.

**Comment by vogloblinsky** [comment]
@arthurevans Thanks for highlighting this.
I will wait SkateJS v6 to update the samples. Current documentation is too light.

**Comment by vogloblinsky** [comment]
- [x] Lit-html fixed
